title: "Substance 3D Designer ノードの中身解読"
summary: "
Substance 3D Designer で理屈を持ってテクスチャ作成したい方向けの本です。
中級者~上級者を対象としています。
この内容を通して、「Houdini Copernicus」でのテクスチャ作成やマテリアル
"
topics: []
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - example1
  - example2
