title: "Substance 3D Designer ノードの中身解析"
summary: "
Substance 3D Designer で理屈を持ってテクスチャ作成したい方向けの本です。

中級者~上級者を対象としています。


本書では Substance 3D Designer のノードの中身を解析し、より深くプロシージャルな画像作成の知識を得ることを目的にしています。

※私がノードの制作者ではないため「解説」ではなく「解析」


標準ノードの中身には基礎的な知識が詰まっています。

それは「Substance 3D Designer」のみならず、以下にも役立ちます。

・「Houdini Copernicus」でのテクスチャ作成

・「ゲームエンジン」でのマテリアル作成
"
topics: [Substance3DDesigner]
published: True
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - example1
  - example2
  - example3

toc_depth: 4